// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUBkDpaOw7OQUN3E888KTO0ro9hH8zSU',
    appId: '1:948249377652:web:dd6b4358e05ff9a2ed4a21',
    messagingSenderId: '948249377652',
    projectId: 'gdg-braynr',
    authDomain: 'gdg-braynr.firebaseapp.com',
    storageBucket: 'gdg-braynr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuzOykSyQX77U3J1lWibcu2NkYrxVufs',
    appId: '1:948249377652:android:7027b441134e8b29ed4a21',
    messagingSenderId: '948249377652',
    projectId: 'gdg-braynr',
    storageBucket: 'gdg-braynr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmZCakT7R8Wk8yFhhr2ws6YvlaSl7mr8',
    appId: '1:948249377652:ios:a3124b57cd9fe43bed4a21',
    messagingSenderId: '948249377652',
    projectId: 'gdg-braynr',
    storageBucket: 'gdg-braynr.firebasestorage.app',
    iosBundleId: 'com.example.gdgBraynr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTmZCakT7R8Wk8yFhhr2ws6YvlaSl7mr8',
    appId: '1:948249377652:ios:a3124b57cd9fe43bed4a21',
    messagingSenderId: '948249377652',
    projectId: 'gdg-braynr',
    storageBucket: 'gdg-braynr.firebasestorage.app',
    iosBundleId: 'com.example.gdgBraynr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJUBkDpaOw7OQUN3E888KTO0ro9hH8zSU',
    appId: '1:948249377652:web:6ac9b9d3249ad5deed4a21',
    messagingSenderId: '948249377652',
    projectId: 'gdg-braynr',
    authDomain: 'gdg-braynr.firebaseapp.com',
    storageBucket: 'gdg-braynr.firebasestorage.app',
  );
}
